### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by necolas** [bvaughn/tweets#1]
Please can you not use "Twitter Lite"

**Comment by bvaughn** [comment]
Sure! Project has been renamed.

Just so you know, I meant no offense by this. It was just a for-fun thing I was working on in the evening as a way of seeing how fast react-virtualized and Preact were together.

In the future, please feel free to reach out to me directly (here or on Twitter). If I offend you, I'm probably totally unaware and not intending to. Passive aggressive isn't my style.

❤️

**Comment by necolas** [comment]
Thanks!

**Comment by bvaughn** [comment]
You're welcome, of course!
